# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballRates', '0002_auto_20180415_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='match',
            name='fixture',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.AddField(
            model_name='match',
            name='competicio',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='match',
            name='golslocal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='golsvisitant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='jornada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='local',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='visitant',
            field=models.TextField(default='', max_length=20),
        ),
    ]
