# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballRates', '0006_auto_20180415_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='golslocal',
        ),
        migrations.RemoveField(
            model_name='match',
            name='golsvisitant',
        ),
    ]
