# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 12:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('footballRates', '0006_auto_20180415_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='MatchEnded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golslocal', models.IntegerField(default=0)),
                ('golsvisitant', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='golslocal',
        ),
        migrations.RemoveField(
            model_name='match',
            name='golsvisitant',
        ),
        migrations.AlterField(
            model_name='playervaloration',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballRates.MatchEnded'),
        ),
        migrations.AddField(
            model_name='matchended',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballRates.Match'),
        ),
        migrations.AddField(
            model_name='cronica',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballRates.MatchEnded'),
        ),
        migrations.AddField(
            model_name='cronica',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
