# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footballRates', '0009_pronostic_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEnded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golslocal', models.IntegerField(default=0)),
                ('golsvisitant', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='golslocal',
        ),
        migrations.RemoveField(
            model_name='match',
            name='golsvisitant',
        ),
        migrations.AddField(
            model_name='matchended',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballRates.Match'),
        ),
    ]
