# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footballRates', '0010_auto_20180430_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playervaloration',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballRates.MatchEnded'),
        ),
    ]
