# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 11:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('footballRates', '0011_auto_20180430_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballRates.MatchEnded')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
